<a href="https://colab.research.google.com/github/sujittra32477/Tools-for-DS-Assignment/blob/main/TestModelProject02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **: Clean & Change Type Data**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel('DataTrain_Model63.xlsx', sheet_name='datacleantoUSE')
df

Sex  Age  BP  Height  Weight    BMI Smoke Drink  TRI_TGBLOOD  FBS_BLOOD  \
0     M   38   2     169      78  27.31    No   Yes          109         85   
1     M   35   1     163      63  23.71    No   Yes           77         85   
2     M   38   2     182      84  25.36   Yes    No          336        100   
3     M   38   3     167      75  26.89   Yes    No          178         84   
4     M   34   2     170      67  23.18    No    No           59         92   
..   ..  ...  ..     ...     ...    ...   ...   ...          ...        ...   
955   F   35   1     158      60  24.03    No    No          104         89   
956   M   49   3     159      56  22.15   Yes   Yes          267        192   
957   M   36   3     175      84  27.43    No   Yes          182         92   
958   M   45   3     161      62  23.92    No   Yes          193         93   
959   M   42   2     164      63  23.42   Yes    No          116        124   

     SGOT  SGPT  ALP  BUN  CREATININE  URIC_ACID  UA  CBC  CDISESE  DLD_CLASS  
0      48    69   73   10         1.1        5.8   0    0        0          1  
1      20    22   84   14         1.1        7.2   0    0        0          1  
2      17    27   58   18         0.9        7.7   0    0        0          1  
3      22    26   83   10         1.1        7.4   0    0        0          1  
4      17    22  120   12         1.1        7.8   0    0        0          1  
..    ...   ...  ...  ...         ...        ...  ..  ...      ...        ...  
955    18     9   54   13         1.0        5.2   0    0        0          1  
956    30    36   87   19         1.5        5.8   0    0        5          1  
957    34    57   74   13         1.2        5.0   0    0        0          1  
958    33    36   57   16         1.3        6.3   0    0        2          1  
959    15    18   69   11         1.2        5.7   0    0        0          1  

[960 rows x 20 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Sex          960 non-null    object 
 1   Age          960 non-null    int64  
 2   BP           960 non-null    int64  
 3   Height       960 non-null    int64  
 4   Weight       960 non-null    int64  
 5   BMI          960 non-null    float64
 6   Smoke        960 non-null    object 
 7   Drink        960 non-null    object 
 8   TRI_TGBLOOD  960 non-null    int64  
 9   FBS_BLOOD    960 non-null    int64  
 10  SGOT         960 non-null    int64  
 11  SGPT         960 non-null    int64  
 12  ALP          960 non-null    int64  
 13  BUN          960 non-null    int64  
 14  CREATININE   960 non-null    float64
 15  URIC_ACID    960 non-null    float64
 16  UA           960 non-null    int64  
 17  CBC          960 non-null    int64  
 18  CDISESE      960 non-null    int64  
 19  DLD_CLAS

In [ ]:
#Change Data Type and Replace Value

df['Sex'] = df['Sex'].replace({'M': 1, 'F': 0})
df['Smoke'] = df['Smoke'].replace({'Yes': 1, 'No': 0})
df['Drink'] = df['Drink'].replace({'Yes': 1, 'No': 0})
df.head()

Sex  Age  BP  Height  Weight    BMI  Smoke  Drink  TRI_TGBLOOD  FBS_BLOOD  \
0    1   38   2     169      78  27.31      0      1          109         85   
1    1   35   1     163      63  23.71      0      1           77         85   
2    1   38   2     182      84  25.36      1      0          336        100   
3    1   38   3     167      75  26.89      1      0          178         84   
4    1   34   2     170      67  23.18      0      0           59         92   

   SGOT  SGPT  ALP  BUN  CREATININE  URIC_ACID  UA  CBC  CDISESE  DLD_CLASS  
0    48    69   73   10         1.1        5.8   0    0        0          1  
1    20    22   84   14         1.1        7.2   0    0        0          1  
2    17    27   58   18         0.9        7.7   0    0        0          1  
3    22    26   83   10         1.1        7.4   0    0        0          1  
4    17    22  120   12         1.1        7.8   0    0        0          1

In [ ]:
def create_age_range(df):               #Create Age Range: create new column Age Range
  conditions = [
        (df['Age'] < 20),
        (df['Age'] >= 20) & (df['Age'] <= 30),
        (df['Age'] >= 31) & (df['Age'] <= 40),
        (df['Age'] >= 41) & (df['Age'] <= 50),
        (df['Age'] >= 51)]
  values = [0, 1, 2, 3, 4]
  df['Age_Range'] = pd.Series(pd.cut(df['Age'], bins=[-float('inf'), 20, 31, 41, 51, float('inf')], labels=values, right=False))
  return df

df = create_age_range(df)
df['Age_Range']

0      2
1      2
2      2
3      2
4      2
      ..
955    2
956    3
957    2
958    3
959    3
Name: Age_Range, Length: 960, dtype: category
Categories (5, int64): [0 < 1 < 2 < 3 < 4]

In [ ]:
def create_BMI_range(df):               #Create BMI Range: create new column BMI Range
  conditions = [
        (df['BMI'] < 18.50),
        (df['BMI'] >= 18.50),
        (df['BMI'] >= 23.01),
        (df['BMI'] >= 25.00),
        (df['BMI'] >= 30.00)]
  values = [1, 2, 3, 4, 5]
  df['BMI_Range'] = pd.Series(pd.cut(df['BMI'], bins=[-float('inf'), 18.50, 23.01, 25.00, 30.00, float('inf')], labels=values, right=False))
  return df

df = create_BMI_range(df)
df['BMI_Range']

0      4
1      3
2      4
3      4
4      3
      ..
955    3
956    2
957    4
958    3
959    3
Name: BMI_Range, Length: 960, dtype: category
Categories (5, int64): [1 < 2 < 3 < 4 < 5]

In [ ]:
def create_CDISESE_range(df):               #Create CDISESE Range: create new column CDISESE Range
  conditions_cdisese = [
        (df['CDISESE'] < 1),
        (df['CDISESE'] >= 1),
        (df['CDISESE'] >= 2),
        (df['CDISESE'] >= 3),
        (df['CDISESE'] >= 4),
        (df['CDISESE'] > 50)]
  values = [0, 3, 1, 2, 5, 4]
  df['CDISESE_Range'] = pd.Series(pd.cut(df['CDISESE'], bins=[-float('inf'), 1, 2, 3, 4, 50, float('inf')], labels=values, right=False))
  return df

df = create_CDISESE_range(df)
df['CDISESE_Range'].head(30)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     2
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    5
17    0
18    0
19    0
20    0
21    5
22    0
23    0
24    0
25    0
26    0
27    0
28    4
29    0
Name: CDISESE_Range, dtype: category
Categories (6, int64): [0 < 3 < 1 < 2 < 5 < 4]

In [ ]:
#Select Column: create DataFrame to Moedling
columns_to_select = ['Sex',	'BP',	'Height',	'Weight',	'Smoke', 'Drink',	'TRI_TGBLOOD',	'FBS_BLOOD',	'SGOT',	'SGPT',
                     'ALP',	'BUN',	'CREATININE',	'URIC_ACID',	'UA',	'CBC',	'Age_Range', 'BMI_Range', 'CDISESE_Range',	'DLD_CLASS']
df2 = df[columns_to_select].copy()
df2

Sex  BP  Height  Weight  Smoke  Drink  TRI_TGBLOOD  FBS_BLOOD  SGOT  \
0      1   2     169      78      0      1          109         85    48   
1      1   1     163      63      0      1           77         85    20   
2      1   2     182      84      1      0          336        100    17   
3      1   3     167      75      1      0          178         84    22   
4      1   2     170      67      0      0           59         92    17   
..   ...  ..     ...     ...    ...    ...          ...        ...   ...   
955    0   1     158      60      0      0          104         89    18   
956    1   3     159      56      1      1          267        192    30   
957    1   3     175      84      0      1          182         92    34   
958    1   3     161      62      0      1          193         93    33   
959    1   2     164      63      1      0          116        124    15   

     SGPT  ALP  BUN  CREATININE  URIC_ACID  UA  CBC Age_Range BMI_Range  \
0      69   73   10         1.1        5.8   0    0         2         4   
1      22   84   14         1.1        7.2   0    0         2         3   
2      27   58   18         0.9        7.7   0    0         2         4   
3      26   83   10         1.1        7.4   0    0         2         4   
4      22  120   12         1.1        7.8   0    0         2         3   
..    ...  ...  ...         ...        ...  ..  ...       ...       ...   
955     9   54   13         1.0        5.2   0    0         2         3   
956    36   87   19         1.5        5.8   0    0         3         2   
957    57   74   13         1.2        5.0   0    0         2         4   
958    36   57   16         1.3        6.3   0    0         3         3   
959    18   69   11         1.2        5.7   0    0         3         3   

    CDISESE_Range  DLD_CLASS  
0               0          1  
1               0          1  
2               0          1  
3               0          1  
4               0          1  
..            ...        ...  
955             0          1  
956             5          1  
957             0          1  
958             1          1  
959             0          1  

[960 rows x 20 columns]

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype   
---  ------         --------------  -----   
 0   Sex            960 non-null    int64   
 1   BP             960 non-null    int64   
 2   Height         960 non-null    int64   
 3   Weight         960 non-null    int64   
 4   Smoke          960 non-null    int64   
 5   Drink          960 non-null    int64   
 6   TRI_TGBLOOD    960 non-null    int64   
 7   FBS_BLOOD      960 non-null    int64   
 8   SGOT           960 non-null    int64   
 9   SGPT           960 non-null    int64   
 10  ALP            960 non-null    int64   
 11  BUN            960 non-null    int64   
 12  CREATININE     960 non-null    float64 
 13  URIC_ACID      960 non-null    float64 
 14  UA             960 non-null    int64   
 15  CBC            960 non-null    int64   
 16  Age_Range      960 non-null    category
 17  BMI_Range      960 non-null    cate

In [ ]:
df2['Age_Range'] = df2['Age_Range'].astype(int)
df2['BMI_Range'] = df['BMI_Range'].astype(int)
df2['CDISESE_Range'] = df2['CDISESE_Range'].astype(int)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Sex            960 non-null    int64  
 1   BP             960 non-null    int64  
 2   Height         960 non-null    int64  
 3   Weight         960 non-null    int64  
 4   Smoke          960 non-null    int64  
 5   Drink          960 non-null    int64  
 6   TRI_TGBLOOD    960 non-null    int64  
 7   FBS_BLOOD      960 non-null    int64  
 8   SGOT           960 non-null    int64  
 9   SGPT           960 non-null    int64  
 10  ALP            960 non-null    int64  
 11  BUN            960 non-null    int64  
 12  CREATININE     960 non-null    float64
 13  URIC_ACID      960 non-null    float64
 14  UA             960 non-null    int64  
 15  CBC            960 non-null    int64  
 16  Age_Range      960 non-null    int64  
 17  BMI_Range      960 non-null    int64  
 18  CDISESE_Ra

# **: Modeling**

In [ ]:
pip install catboost

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
import lightgbm as lgb

In [ ]:
x = df2.drop('DLD_CLASS', axis=1)   # Features
y = df2['DLD_CLASS']                # Target variable

# Split the dataset into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

# Initialize classifiers
classifiers = {
    'Random Forest': RandomForestClassifier(random_state = 42),
    'Decision Tree': DecisionTreeClassifier(random_state = 42),
    'Logistic Regression': LogisticRegression(random_state = 42),
    'XGBoost': XGBClassifier(random_state = 42),
    'LightGBM': lgb.LGBMClassifier(random_state = 42)
    }

In [ ]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 768 entries, 302 to 102
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Sex            768 non-null    int64  
 1   BP             768 non-null    int64  
 2   Height         768 non-null    int64  
 3   Weight         768 non-null    int64  
 4   Smoke          768 non-null    int64  
 5   Drink          768 non-null    int64  
 6   TRI_TGBLOOD    768 non-null    int64  
 7   FBS_BLOOD      768 non-null    int64  
 8   SGOT           768 non-null    int64  
 9   SGPT           768 non-null    int64  
 10  ALP            768 non-null    int64  
 11  BUN            768 non-null    int64  
 12  CREATININE     768 non-null    float64
 13  URIC_ACID      768 non-null    float64
 14  UA             768 non-null    int64  
 15  CBC            768 non-null    int64  
 16  Age_Range      768 non-null    int64  
 17  BMI_Range      768 non-null    int64  
 18  CDISESE_

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score

# Train and evaluate each classifier
for name, clf in classifiers.items():

    # Train the model
    clf.fit(x_train, y_train)

    # Make predictions on the test set
    y_pred = clf.predict(x_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    classification_report_result = classification_report(y_test, y_pred)
    confusion = confusion_matrix(y_test, y_pred)  # Change y_true to y_test

    # Display the evaluation metrics
    print(f"\nEvaluation for {name}:")
    print(f"Accuracy: {accuracy}")
    print("Classification Report:")
    print(classification_report_result)
    print(confusion)

    # Cross-validation scores
    cv_scores = cross_val_score(clf, x, y, cv=5)
    print(f"Cross-validation scores for {name}: {cv_scores}")
    print(f"Mean Cross-validation score for {name}: {cv_scores.mean()}")



Evaluation for Random Forest:
Accuracy: 0.8125
Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.28      0.36        36
           1       0.85      0.94      0.89       156

    accuracy                           0.81       192
   macro avg       0.67      0.61      0.62       192
weighted avg       0.78      0.81      0.79       192

[[ 10  26]
 [ 10 146]]
Cross-validation scores for Random Forest: [0.78125    0.77604167 0.76041667 0.765625   0.76041667]
Mean Cross-validation score for Random Forest: 0.7687499999999999

Evaluation for Decision Tree:
Accuracy: 0.7708333333333334
Classification Report:
              precision    recall  f1-score   support

           0       0.40      0.47      0.44        36
           1       0.87      0.84      0.86       156

    accuracy                           0.77       192
   macro avg       0.64      0.66      0.65       192
weighted avg       0.79      0.77      0.78       192

[[ 

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

Cross-validation scores for Logistic Regression: [0.78125    0.80208333 0.734375   0.79166667 0.78645833]
Mean Cross-validation score for Logistic Regression: 0.7791666666666667

Evaluation for XGBoost:
Accuracy: 0.7708333333333334
Classification Report:
              precision    recall  f1-score   support

           0       0.38      0.33      0.35        36
           1       0.85      0.87      0.86       156

    accuracy                           0.77       192
   macro avg       0.61      0.60      0.61       192
weighted avg       0.76      0.77      0.77       192

[[ 12  24]
 [ 20 136]]
Cross-validation scores for XGBoost: [0.75520833 0.77083333 0.734375   0.78645833 0.75      ]
Mean Cross-validation score for XGBoost: 0.7593750000000001
[LightGBM] [Info] Number of positive: 593, number of negative: 175
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000153 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memor

In [ ]:
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import cross_val_score

# Create Model CatBoostClassifier
cat = CatBoostClassifier(random_state=42)

# Train the model
cat.fit(x_train, y_train)

# Make predictions on the test set
y_pred = cat.predict(x_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
classification_report_result = classification_report(y_test, y_pred)
confusion01 = confusion_matrix(y_test, y_pred)


# Display the evaluation metrics
print(f"\nEvaluation for CatBoost:")
print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(classification_report_result)
print(confusion01)


Learning rate set to 0.009204
0:	learn: 0.6831053	total: 48.7ms	remaining: 48.7s
1:	learn: 0.6731106	total: 51.1ms	remaining: 25.5s
2:	learn: 0.6628856	total: 53ms	remaining: 17.6s
3:	learn: 0.6554609	total: 54.7ms	remaining: 13.6s
4:	learn: 0.6488818	total: 56.4ms	remaining: 11.2s
5:	learn: 0.6391462	total: 58.5ms	remaining: 9.69s
6:	learn: 0.6329916	total: 60.4ms	remaining: 8.56s
7:	learn: 0.6240187	total: 62.2ms	remaining: 7.72s
8:	learn: 0.6181147	total: 64.1ms	remaining: 7.05s
9:	learn: 0.6113831	total: 66.4ms	remaining: 6.57s
10:	learn: 0.6060830	total: 68.1ms	remaining: 6.12s
11:	learn: 0.6004094	total: 69.9ms	remaining: 5.75s
12:	learn: 0.5938211	total: 71.7ms	remaining: 5.44s
13:	learn: 0.5858054	total: 73.7ms	remaining: 5.19s
14:	learn: 0.5786336	total: 75.5ms	remaining: 4.96s
15:	learn: 0.5722713	total: 77.6ms	remaining: 4.77s
16:	learn: 0.5664271	total: 82.4ms	remaining: 4.76s
17:	learn: 0.5598591	total: 87.7ms	remaining: 4.78s
18:	learn: 0.5551766	total: 91.1ms	remaining: 

In [ ]:
# Cross-validation scores for CatBoost
cv_scores = cross_val_score(cat, x, y, cv=5)
print(f"Cross-validation scores for CatBoost: {cv_scores}")
print(f"Mean Cross-validation score for CatBoost: {cv_scores.mean()}")

เอาต์พุตของการสตรีมมีการตัดเหลือเพียง 5000 บรรทัดสุดท้าย
6:	learn: 0.6382321	total: 15.1ms	remaining: 2.14s
7:	learn: 0.6293647	total: 17.2ms	remaining: 2.14s
8:	learn: 0.6227891	total: 19.5ms	remaining: 2.15s
9:	learn: 0.6158243	total: 21.1ms	remaining: 2.09s
10:	learn: 0.6098979	total: 22.9ms	remaining: 2.06s
11:	learn: 0.6044317	total: 25.9ms	remaining: 2.13s
12:	learn: 0.5981047	total: 27.7ms	remaining: 2.1s
13:	learn: 0.5944541	total: 29.4ms	remaining: 2.07s
14:	learn: 0.5873924	total: 31.3ms	remaining: 2.06s
15:	learn: 0.5808405	total: 33.1ms	remaining: 2.03s
16:	learn: 0.5747130	total: 34.9ms	remaining: 2.02s
17:	learn: 0.5696497	total: 36.7ms	remaining: 2s
18:	learn: 0.5645400	total: 38.6ms	remaining: 2s
19:	learn: 0.5598436	total: 40.5ms	remaining: 1.98s
20:	learn: 0.5560911	total: 42.4ms	remaining: 1.97s
21:	learn: 0.5513684	total: 44.3ms	remaining: 1.97s
22:	learn: 0.5431230	total: 46.1ms	remaining: 1.96s
23:	learn: 0.5398146	total: 48ms	remaining: 1.95s
24:	learn: 0.5335041

# **: Save Model to use**

In [ ]:
# Train and fit the model: random forest classifier
rforest_clf = RandomForestClassifier().fit(x_train, y_train)

# Evaluate the model's accuracy
print("For Random Forest model:")
print("Train set accuracy = " + str(rforest_clf.score(x_train, y_train)))
print("Test set accuracy = " + str(rforest_clf.score(x_test, y_test)))

# Determine features' importances
# get importance
importance = rforest_clf.feature_importances_
# summarize feature importance
for i,v in enumerate(importance):
	print('Feature: %0d, Score: %.5f' % (i,v))


For Random Forest model:
Train set accuracy = 1.0
Test set accuracy = 0.8020833333333334
Feature: 0, Score: 0.00708
Feature: 1, Score: 0.02449
Feature: 2, Score: 0.05949
Feature: 3, Score: 0.07873
Feature: 4, Score: 0.01421
Feature: 5, Score: 0.01467
Feature: 6, Score: 0.27765
Feature: 7, Score: 0.07061
Feature: 8, Score: 0.06189
Feature: 9, Score: 0.07606
Feature: 10, Score: 0.06767
Feature: 11, Score: 0.05337
Feature: 12, Score: 0.03954
Feature: 13, Score: 0.07611
Feature: 14, Score: 0.00250
Feature: 15, Score: 0.00856
Feature: 16, Score: 0.01859
Feature: 17, Score: 0.02508
Feature: 18, Score: 0.02369


In [ ]:
!pip show pickle

In [ ]:
!pip install scikit-learn==1.4.1.post1

In [ ]:
import pickle
rf_model = classifiers['Random Forest']

with open(f'random_forest_model.pkl', 'wb') as file:
    pickle.dump(rf_model, file)


In [ ]:
logis_model = classifiers['Logistic Regression']

with open(f'logis_model.pkl', 'wb') as file:
    pickle.dump(logis_model, file)


In [ ]:
import sklearn
print(sklearn.__version__)

1.4.1.post1


In [ ]:
predicted_prob = rf_model.predict_proba([[0,2,169,78,0,1,109,85,48,69,73,10,1.1,5.8,0,0,2,4,0]])
prob_of_positive_class = predicted_prob[0][1]
print(prob_of_positive_class)

0.81


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
predicted_probabilities = rf_model.predict_proba([[0,2,169,78,0,1,109,85,48,69,73,10,1.1,5.8,0,0,2,4,0]])
probability_of_negative_class = predicted_probabilities[0][0]
print(probability_of_negative_class)

0.19


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
predicted_probabilities = rf_model.predict_proba([[0,2,153,60,0,0,86,75,16,24,55,13,1.1,4.5,0,1,2,4,0]])
probability_of_positive_class = predicted_probabilities[0][1]
print(probability_of_positive_class)

0.17


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
predicted_probabilities = rf_model.predict_proba([[0,2,153,60,0,0,86,75,16,24,55,13,1.1,4.5,0,1,2,4,0]])
probability_of_negative_class = predicted_probabilities[0][0]
print(probability_of_negative_class)

0.83


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
print(logis_model.predict_proba([[0,2,2,169,78,4,0,1,109,85,48,69,73,10,1.1,5.8,0,0,0]]))

[[1.00000000e+00 4.09140336e-22]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


**Assesment Risk**

In [ ]:
mean_dld_class = df2['DLD_CLASS'].mean()
print(mean_dld_class)


0.7802083333333333


In [ ]:
premium = (6800 + (6800 * mean_dld_class))/(1 - 0.1 - 0.25 - 0.05)
print(premium)

20175.694444444445


# **: Test Model**

In [ ]:
data61 = pd.read_csv('DataModel61.csv')
data61.head()

ID  Gender Age_Range Blood_Pressure_Original_TH Height Weight    BMI  \
0  00001       1         -           ความดันโลหิตปกติ    171     68  23.26   
1  12314       0         -    ความดันโลหิตสูงเล็กน้อย    160     73  28.52   
2  05973       1         -            ความดันโลหิตสูง    165     73  26.81   
3  08599       0         -    ความดันโลหิตสูงเล็กน้อย    157     72  29.21   
4  05584       1         -            ความดันโลหิตสูง    164     67  24.91   

   Smoking  Drinking  TRI  ... Creatinine Uric_Acid Urinalysis_Result  \
0      1.0       0.0  310  ...        1.3       4.2                 1   
1      0.0       0.0   49  ...          -         -                 0   
2      0.0       1.0  162  ...        1.1       5.2                 0   
3      0.0       0.0  139  ...          -         -                 0   
4      0.0       0.0  137  ...          1       3.5                 0   

  Blood_Test_Result CDISESE Total_Fat_Level AgeRange61  BMIRange61  \
0                 0       3               1        NaN           3   
1                 0       0               0        NaN           4   
2                 0       0               1        NaN           4   
3                 0       0               1        NaN           4   
4                 0       0               1        NaN           3   

   CDISESERange61  BP  
0               2   1  
1               0   2  
2               0   3  
3               0   2  
4               0   3  

[5 rows x 25 columns]

In [ ]:
data62 = pd.read_csv('DataModel62.csv')
data62.head()

ID  Gender Age_Range Blood_Pressure_Original_TH Height Weight    BMI  \
0  04373       1         -    ความดันโลหิตสูงเล็กน้อย    165   82.3  30.23   
1  06701       1         -           ความดันโลหิตปกติ    167     61  21.87   
2  06700       0         -    ความดันโลหิตสูงเล็กน้อย    162   57.1  21.76   
3  06763       1         -            ความดันโลหิตสูง    169   62.8  21.99   
4  06734       1         -    ความดันโลหิตสูงเล็กน้อย    170   75.7  26.19   

   Smoking  Drinking  TRI  ...  Creatinine  Uric_Acid  Urinalysis_Result  \
0      NaN       NaN   62  ...        1.13        5.5                  0   
1      NaN       NaN   97  ...        1.27        6.8                  0   
2      NaN       NaN  118  ...        0.73          5                  0   
3      NaN       NaN  131  ...        0.84        5.6                  0   
4      NaN       NaN  110  ...        1.19        6.5                  0   

  Blood_Test_Result CDISESE Total_Fat_Level AgeRange62  BMIRange62  \
0                 0      99               1         99           5   
1                 0      99               1         99           2   
2                 0      99               1         99           2   
3                 0      99               1         99           2   
4                 0      99               1         99           4   

   CDISESERange62  BP  
0              99   2  
1              99   1  
2              99   2  
3              99   3  
4              99   2  

[5 rows x 25 columns]

In [ ]:
data63 = pd.read_csv('DataModel63.csv')
data63.head()

ID  Gender Age_Range Blood_Pressure_Original_TH Height Weight BMI  \
0  10320       1         -           ความดันโลหิตปกติ      -      -   -   
1  11096       1         -           ความดันโลหิตปกติ      -      -   -   
2  05570       1         -            ความดันโลหิตสูง      -      -   -   
3  04941       1         -           ความดันโลหิตปกติ      -      -   -   
4  05394       1         -           ความดันโลหิตปกติ      -      -   -   

   Smoking  Drinking  TRI  ... Creatinine Uric_Acid Urinalysis_Result  \
0      NaN       NaN  123  ...        1.1       9.2                 0   
1      NaN       NaN  148  ...       1.04       6.6                 0   
2      NaN       NaN   64  ...       0.95       6.2                 0   
3      NaN       NaN  236  ...       0.95       8.6                 0   
4      NaN       NaN   63  ...       0.97       5.1                 0   

  Blood_Test_Result CDISESE Total_Fat_Level AgeRange63  BMIRange63  \
0                 0       0               1         99          99   
1                 0       0               0         99          99   
2                 9       0               1         99          99   
3                 0       0               1         99          99   
4                 0       0               0         99          99   

   CDISESERange63  BP  
0               0   1  
1               0   1  
2               0   3  
3               0   1  
4               0   1  

[5 rows x 25 columns]

In [ ]:
data61.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2387 entries, 0 to 2386
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   ID                          2387 non-null   object 
 1   Gender                      2387 non-null   int64  
 2   Age_Range                   2387 non-null   object 
 3   Blood_Pressure_Original_TH  2387 non-null   object 
 4   Height                      2387 non-null   object 
 5   Weight                      2387 non-null   object 
 6   BMI                         2387 non-null   object 
 7   Smoking                     2371 non-null   float64
 8   Drinking                    2371 non-null   float64
 9   TRI                         2387 non-null   object 
 10  FBS                         2387 non-null   object 
 11  SGOT                        2387 non-null   object 
 12  SGPT                        2387 non-null   object 
 13  ALK_PHOSPHATASE             2387 

In [ ]:
column_select_test61 = ['Gender', 'BP', 'Height', 'Weight', 'Smoking', 'Drinking',
                   'TRI', 'FBS', 'SGOT', 'SGPT', 'ALK_PHOSPHATASE', 'BUN', 'Creatinine',
                   'Uric_Acid',	'Urinalysis_Result',	'Blood_Test_Result',	'AgeRange61',
                   'BMIRange61', 'CDISESERange61', 'Total_Fat_Level']
df61 = data61[column_select_test61].copy()

new_name_column = {'Gender':'Sex',
                   'Smoking':'Smoke',
                   'Drinking':'Drink',
                   'TRI':'TRI_TGBLOOD',
                   'FBS':'FBS_BLOOD',
                   'ALK_PHOSPHATASE':'ALP',
                   'Creatinine':'CREATININE',
                   'Uric_Acid':'URIC_ACID',
                   'Urinalysis_Result':'UA',
                   'Blood_Test_Result':'CBC',
                   'AgeRange61':'Age_Range',
                   'BMIRange61':'BMI_Range',
                   'CDISESERange61':'CDISESE_Range',
                   'Total_Fat_Level':'DLD_CLASS'}
df61.rename(columns=new_name_column, inplace=True)
df61[df61 == '-'] = np.NaN
df61

Sex  BP Height Weight  Smoke  Drink TRI_TGBLOOD FBS_BLOOD SGOT SGPT  \
0       1   1    171     68    1.0    0.0         310       189   50   58   
1       0   2    160     73    0.0    0.0          49        74   17   16   
2       1   3    165     73    0.0    1.0         162        92   17   11   
3       0   2    157     72    0.0    0.0         139       184   26   42   
4       1   3    164     67    0.0    0.0         137        86   23   25   
...   ...  ..    ...    ...    ...    ...         ...       ...  ...  ...   
2382    1   2    180     92    0.0    1.0         200        87   23   28   
2383    1   3    182    101    0.0    1.0         132        88   24   26   
2384    0   2    158     63    0.0    0.0          74        83   15   19   
2385    0   1    158     57    0.0    0.0         127        82   16   10   
2386    1   1    168     68    0.0    0.0          88       110   25   30   

      ALP  BUN CREATININE URIC_ACID  UA  CBC  Age_Range  BMI_Range  \
0      92   15        1.3       4.2   1    0        NaN          3   
1     NaN  NaN        NaN       NaN   0    0        NaN          4   
2     106   11        1.1       5.2   0    0        NaN          4   
3     NaN  NaN        NaN       NaN   0    0        NaN          4   
4      71   15          1       3.5   0    0        NaN          3   
...   ...  ...        ...       ...  ..  ...        ...        ...   
2382  NaN  NaN        NaN       NaN   0    0        NaN          4   
2383  NaN  NaN        NaN       NaN   0    0        NaN          5   
2384   50   12          1       5.5   0    0        NaN          4   
2385  NaN  NaN        NaN       NaN   0    0        NaN          2   
2386  NaN  NaN        NaN       NaN   0    0        NaN          3   

      CDISESE_Range  DLD_CLASS  
0                 2          1  
1                 0          0  
2                 0          1  
3                 0          1  
4                 0          1  
...             ...        ...  
2382              0          1  
2383              0          1  
2384              0          1  
2385              0          0  
2386              0          1  

[2387 rows x 20 columns]

In [ ]:
column_select_test62 = ['Gender', 'BP', 'Height', 'Weight', 'Smoking', 'Drinking',
                   'TRI', 'FBS', 'SGOT', 'SGPT', 'ALK_PHOSPHATASE', 'BUN', 'Creatinine',
                   'Uric_Acid',	'Urinalysis_Result', 'Blood_Test_Result',	'AgeRange62',
                   'BMIRange62', 'CDISESERange62', 'Total_Fat_Level']
df62 = data62[column_select_test62].copy()

new_name_column = {'Gender':'Sex',
                   'Smoking':'Smoke',
                   'Drinking':'Drink',
                   'TRI':'TRI_TGBLOOD',
                   'FBS':'FBS_BLOOD',
                   'ALK_PHOSPHATASE':'ALP',
                   'Creatinine':'CREATININE',
                   'Uric_Acid':'URIC_ACID',
                   'Urinalysis_Result':'UA',
                   'Blood_Test_Result':'CBC',
                   'AgeRange62':'Age_Range',
                   'BMIRange62':'BMI_Range',
                   'CDISESERange62':'CDISESE_Range',
                   'Total_Fat_Level':'DLD_CLASS'}
df62.rename(columns=new_name_column, inplace=True)
df62[df62 == '-'] = np.NaN
df62

Sex  BP Height Weight  Smoke  Drink  TRI_TGBLOOD  FBS_BLOOD  SGOT  SGPT  \
0       1   2    165   82.3    NaN    NaN           62        101    20    26   
1       1   1    167     61    NaN    NaN           97         91    21     8   
2       0   2    162   57.1    NaN    NaN          118         92    26    19   
3       1   3    169   62.8    NaN    NaN          131         97    26    29   
4       1   2    170   75.7    NaN    NaN          110        111    18    13   
...   ...  ..    ...    ...    ...    ...          ...        ...   ...   ...   
2541    1   1    163     62    0.0    0.0          180         90    21    39   
2542    1   2    172     65    0.0    0.0           58         96    24    44   
2543    1   2    171     64    0.0    0.0          157        258    16    32   
2544    1   2    180    103    0.0    0.0          143         87    26    67   
2545    0   2    159     58    0.0    0.0          103         87    20    19   

      ALP  BUN CREATININE URIC_ACID  UA  CBC  Age_Range  BMI_Range  \
0     NaN   12       1.13       5.5   0    0         99          5   
1     NaN   15       1.27       6.8   0    0         99          2   
2     NaN   12       0.73         5   0    0         99          2   
3     NaN   13       0.84       5.6   0    0         99          2   
4     NaN   13       1.19       6.5   0    0         99          4   
...   ...  ...        ...       ...  ..  ...        ...        ...   
2541   48   14        1.1       6.6   0    0         99          3   
2542  NaN  NaN        NaN       NaN   1    0         99          2   
2543   45   15        0.9       3.6   1    0         99          2   
2544  NaN  NaN        NaN       NaN   0    0         99          5   
2545   43   10        0.8       4.7   0    1         99          2   

      CDISESE_Range  DLD_CLASS  
0                99          1  
1                99          1  
2                99          1  
3                99          1  
4                99          1  
...             ...        ...  
2541              0          1  
2542              0          1  
2543              0          1  
2544              0          1  
2545              0          1  

[2546 rows x 20 columns]

In [ ]:
column_select_test63 = ['ID','Gender', 'BP', 'Height', 'Weight', 'Smoking', 'Drinking',
                   'TRI', 'FBS', 'SGOT', 'SGPT', 'ALK_PHOSPHATASE', 'BUN', 'Creatinine',
                   'Uric_Acid',	'Urinalysis_Result',	'Blood_Test_Result',	'AgeRange63',
                   'BMIRange63', 'CDISESERange63', 'Total_Fat_Level']
df63 = data63[column_select_test63].copy()
df63.drop_duplicates(subset='ID', keep='first', inplace=True)

new_name_column = {'Gender':'Sex',
                   'Smoking':'Smoke',
                   'Drinking':'Drink',
                   'TRI':'TRI_TGBLOOD',
                   'FBS':'FBS_BLOOD',
                   'ALK_PHOSPHATASE':'ALP',
                   'Creatinine':'CREATININE',
                   'Uric_Acid':'URIC_ACID',
                   'Urinalysis_Result':'UA',
                   'Blood_Test_Result':'CBC',
                   'AgeRange63':'Age_Range',
                   'BMIRange63':'BMI_Range',
                   'CDISESERange63':'CDISESE_Range',
                   'Total_Fat_Level':'DLD_CLASS'}
df63.rename(columns=new_name_column, inplace=True)
df63[df63 == '-'] = np.NaN
df63

ID  Sex  BP  Height Weight  Smoke  Drink TRI_TGBLOOD FBS_BLOOD SGOT  \
0     10320    1   1     NaN    NaN    NaN    NaN         123       112   48   
1     11096    1   1     NaN    NaN    NaN    NaN         148       140   16   
2     05570    1   3     NaN    NaN    NaN    NaN          64       103   21   
3     04941    1   1     NaN    NaN    NaN    NaN         236       107   23   
4     05394    1   1     NaN    NaN    NaN    NaN          63       106   16   
...     ...  ...  ..     ...    ...    ...    ...         ...       ...  ...   
1960  09836    1  99     NaN    NaN    NaN    NaN         110       108   16   
1961  09869    1   2  173.00  73.00    0.0    1.0         118        76   25   
1962  09963    0   2  156.00  56.00    0.0    0.0          89        91   20   
1963  09966    1   2  174.00  67.00    0.0    1.0         188        83   36   
1964  09970    1   3  162.00  78.00    0.0    0.0         184        98   24   

      ...  ALP  BUN CREATININE URIC_ACID UA  CBC  Age_Range  BMI_Range  \
0     ...  NaN   16        1.1       9.2  0    0         99         99   
1     ...  NaN   16       1.04       6.6  0    0         99         99   
2     ...  NaN   13       0.95       6.2  0    9         99         99   
3     ...  NaN   11       0.95       8.6  0    0         99         99   
4     ...  NaN   10       0.97       5.1  0    0         99         99   
...   ...  ...  ...        ...       ... ..  ...        ...        ...   
1960  ...  NaN  NaN        NaN       NaN  0    0          2         99   
1961  ...  NaN  NaN        NaN       NaN  0    0          2          3   
1962  ...  NaN  NaN        NaN       NaN  0    1          2          3   
1963  ...  NaN  NaN        NaN       NaN  0    0          2          2   
1964  ...  NaN  NaN        NaN       NaN  0    0          2          4   

      CDISESE_Range  DLD_CLASS  
0                 0          1  
1                 0          0  
2                 0          1  
3                 0          1  
4                 0          0  
...             ...        ...  
1960             99          1  
1961              0          1  
1962              0          1  
1963              0          1  
1964              0          1  

[1965 rows x 21 columns]

## **: Test Model Data 61**



In [ ]:
x61 = df61.drop('DLD_CLASS', axis=1)   # Features
y61 = df61['DLD_CLASS']                # Target variable

In [ ]:
import pickle
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

with open('random_forest_model.pkl', 'rb') as file:
    model = pickle.load(file)

y_pred61 = model.predict(x61)
accuracy = accuracy_score(y61, y_pred61)
classification_report_result = classification_report(y61, y_pred61)
confusion = confusion_matrix(y61, y_pred61)

# Display the evaluation metrics
print("\nEvaluation:")
print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(classification_report_result)
print("Confusion Matrix:")
print(confusion)



Evaluation:
Accuracy: 0.7310431503979891
Classification Report:
              precision    recall  f1-score   support

           0       0.62      0.24      0.34       701
           1       0.75      0.94      0.83      1682
           9       0.00      0.00      0.00         4

    accuracy                           0.73      2387
   macro avg       0.45      0.39      0.39      2387
weighted avg       0.71      0.73      0.69      2387

Confusion Matrix:
[[ 168  533    0]
 [ 105 1577    0]
 [   0    4    0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


## **: Test Model Data 62**



In [ ]:
x62 = df62.drop('DLD_CLASS', axis=1)
y62 = df62['DLD_CLASS']

import pickle
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

with open('random_forest_model.pkl', 'rb') as file:
    model = pickle.load(file)

y_pred62 = model.predict(x62)
accuracy = accuracy_score(y62, y_pred62)
classification_report_result = classification_report(y62, y_pred62)
confusion = confusion_matrix(y62, y_pred62)

# Display the evaluation metrics
print("\nEvaluation:")
print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(classification_report_result)
print("Confusion Matrix:")
print(confusion)


Evaluation:
Accuracy: 0.7140612725844462
Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.52      0.51       731
           1       0.80      0.79      0.80      1815

    accuracy                           0.71      2546
   macro avg       0.65      0.66      0.65      2546
weighted avg       0.72      0.71      0.72      2546

Confusion Matrix:
[[ 380  351]
 [ 377 1438]]


## **: Test Model Data 63**



In [ ]:
x63 = df63.drop(['ID','DLD_CLASS'], axis=1)
y63 = df63['DLD_CLASS']

import pickle
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

with open('random_forest_model.pkl', 'rb') as file:
    model = pickle.load(file)

y_pred63 = model.predict(x63)
accuracy = accuracy_score(y63, y_pred63)
classification_report_result = classification_report(y63, y_pred63)
confusion = confusion_matrix(y63, y_pred63)

# Display the evaluation metrics
print("\nEvaluation:")
print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(classification_report_result)
print("Confusion Matrix:")
print(confusion)


Evaluation:
Accuracy: 0.8198473282442749
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.46      0.59       545
           1       0.82      0.96      0.88      1418
           9       0.00      0.00      0.00         2

    accuracy                           0.82      1965
   macro avg       0.54      0.47      0.49      1965
weighted avg       0.82      0.82      0.80      1965

Confusion Matrix:
[[ 252  293    0]
 [  59 1359    0]
 [   0    2    0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# **: NOTE**

In [ ]:
import xgboost as xgb
boost = xgb.XGBClassifier (random_state = 42, learning_rate = 0.02)
boost.fit (x_train, y_train)
boost.score (x_test, y_test)
class_predictions = boost.predict(x_test)
class_report = classification_report(y_test, class_predictions)
print('XGBoost')
print(f'Classification Report:\n {class_report}')

XGBoost
Classification Report:
               precision    recall  f1-score   support

           0       0.42      0.14      0.21        36
           1       0.83      0.96      0.89       156

    accuracy                           0.80       192
   macro avg       0.62      0.55      0.55       192
weighted avg       0.75      0.80      0.76       192



In [ ]:
import lightgbm as lgb
lightGBM = lgb.LGBMClassifier()
lightGBM.fit(x_train, y_train)
lightGBM.score (x_test, y_test)
class_predictions = lightGBM.predict(x_test)
class_report = classification_report(y_test, class_predictions)
print(f'Classification Report:\n {class_report}')

[LightGBM] [Info] Number of positive: 593, number of negative: 175
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000169 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 679
[LightGBM] [Info] Number of data points in the train set: 768, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.772135 -> initscore=1.220408
[LightGBM] [Info] Start training from score 1.220408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[

In [ ]:

#Note

x = df2.drop('DLD_CLASS', axis=1)   # Features
y = df2['DLD_CLASS']                # Target variable

# Split the dataset into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

# Initialize classifiers
classifiers = {
    'Random Forest': RandomForestClassifier(random_state = 42),
    'Decision Tree': DecisionTreeClassifier(random_state = 42),
    'Logistic Regression': LogisticRegression(random_state = 42),
    'XGBoost': XGBClassifier(random_state = 42),
    'LightGBM': lgb.LGBMClassifier(random_state = 42),
    'CatBoost': CatBoostClassifier(random_state = 42)}